# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='others',
            field=models.ManyToManyField(related_name='posers', to='belt_app.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='plan_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justme', to='belt_app.User'),
        ),
    ]
