# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(default='%m/%d/%y'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='others',
            field=models.ManyToManyField(related_name='others', to='belt_app.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateTimeField(default='%m/%d/%y'),
        ),
    ]
