# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20180126_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 20, 50, 40, 341924)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 27, 20, 50, 40, 341894)),
        ),
    ]
